#!/bin/bash
# Informar a classe do carro conforme solicitação do usuario
declare NOME
echo 
echo "Bem vindo ao consulta classe do carro"
echo
echo "Carros disponiveis"
echo "Ferrari"
echo "Lamborghini"
echo "Celta"
echo "Palio"
echo "Uno"
echo
echo "Digite o nome do carro: "
read NOME

if [ "$NOME" = "ferrari" -o "$NOME" = "lamborghini" ]
then
       echo "Este carro pertence a classe A"

elif [ "$NOME" = "celta" ];
then 
       echo "Este carro pertence a classe B"

elif [ "$NOME" = "palio" -o "$NOME" = "uno" ];
then 
       echo "Este carro pertence a classe C"
fi
exit 0








