#!/bin/bash
#CRIA ARQUIVOS COM NOMES ALEATORIOS 

declare CONTADOR=1
declare SUFIXO

while [ "$CONTADOR" -le 10 ]
do
       SUFIXO="$RANDOM"
       touch "arq-$SUFIXO.txt"
       CONTADOR=$(($CONTADOR + 1))
done  

